version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
  twitttervotes:
    build: ./twitttervotes
    volumes:
      - ./:/go/src/MrFuku/socialpool
    depends_on:
      - mongo
      - nsqlookupd
    ports:
      - "8080:8080"
  counter:
    build: ./counter
    volumes:
      - ./:/go/src/MrFuku/socialpool
    depends_on:
      - mongo
      - nsqlookupd
    ports:
      - "8082:8082"
  api:
    build: ./api
    restart: always
    volumes:
      - ./:/go/src/MrFuku/socialpool
    depends_on:
      - mongo
      - nsqlookupd
    ports:
      - "8083:8083"
  web:
    build: ./web
    restart: always
    volumes:
      - ./:/go/src/MrFuku/socialpool
    depends_on:
      - api
    ports:
      - "8084:8084"
